// THIS FILE IS AUTOMATICALLY GENERATED BY scripts/generate-materials.js
// DO NOT EDIT THIS FILE MANUALLY

export interface MaterialItem {
  id: string;
  title: string;
  filename: string;
  type: 'HTML' | 'PDF' | 'DOCX' | 'PPTX' | 'IMAGE' | 'OTHER';
  extension: string;
  url: string;
  sizeInBytes: number;
}

export interface CourseData {
  id: string;
  code: string;
  title: string;
  chapters: MaterialItem[];
  others: MaterialItem[];
}

export const generatedCourses: CourseData[] = [
  {
    "id": "cse-302",
    "code": "CSE 302",
    "title": "CSE 302",
    "chapters": [
      {
        "id": "1.DBMS_Intro.pdf",
        "title": "1.DBMS Intro",
        "filename": "1.DBMS_Intro.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20302/Chapters/1.DBMS_Intro.pdf",
        "sizeInBytes": 1416396
      }
    ],
    "others": []
  },
  {
    "id": "cse-345",
    "code": "CSE 345",
    "title": "CSE 345",
    "chapters": [
      {
        "id": "ch-3-4.pdf",
        "title": "Ch 3 4",
        "filename": "ch-3-4.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20345/Chapters/ch-3-4.pdf",
        "sizeInBytes": 12014109
      }
    ],
    "others": [
      {
        "id": "chapter_1_2_complete_guide.html",
        "title": "Chapter 1 2 Complete Guide",
        "filename": "chapter_1_2_complete_guide.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20345/Others/chapter_1_2_complete_guide.html",
        "sizeInBytes": 89765
      }
    ]
  },
  {
    "id": "gen-209",
    "code": "GEN 209",
    "title": "GEN 209",
    "chapters": [],
    "others": []
  }
];
