// THIS FILE IS AUTOMATICALLY GENERATED BY scripts/generate-materials.js
// DO NOT EDIT THIS FILE MANUALLY

export interface MaterialItem {
  id: string;
  title: string;
  filename: string;
  type: 'HTML' | 'PDF' | 'DOCX' | 'PPTX' | 'IMAGE' | 'OTHER';
  extension: string;
  url: string;
  sizeInBytes: number;
}

export interface CourseData {
  id: string;
  code: string;
  title: string;
  chapters: MaterialItem[];
  others: MaterialItem[];
}

export const generatedCourses: CourseData[] = [
  {
    "id": "cse-302",
    "code": "CSE 302",
    "title": "CSE 302",
    "chapters": [
      {
        "id": "1.DBMS_Intro.pdf",
        "title": "1.DBMS Intro",
        "filename": "1.DBMS_Intro.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20302/Chapters/1.DBMS_Intro.pdf",
        "sizeInBytes": 1416396
      },
      {
        "id": "2.DBMS_Archi_Schema.pdf",
        "title": "2.DBMS Archi Schema",
        "filename": "2.DBMS_Archi_Schema.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20302/Chapters/2.DBMS_Archi_Schema.pdf",
        "sizeInBytes": 1126603
      },
      {
        "id": "3.1.Relational Model.pdf",
        "title": "3.1.Relational Model",
        "filename": "3.1.Relational Model.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20302/Chapters/3.1.Relational%20Model.pdf",
        "sizeInBytes": 1111277
      },
      {
        "id": "3.2.Relational Model Reference.pdf",
        "title": "3.2.Relational Model Reference",
        "filename": "3.2.Relational Model Reference.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20302/Chapters/3.2.Relational%20Model%20Reference.pdf",
        "sizeInBytes": 1026590
      },
      {
        "id": "4.Relational Algebra.pdf",
        "title": "4.Relational Algebra",
        "filename": "4.Relational Algebra.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20302/Chapters/4.Relational%20Algebra.pdf",
        "sizeInBytes": 2849142
      }
    ],
    "others": [
      {
        "id": "ch 3.html",
        "title": "Ch 3",
        "filename": "ch 3.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20302/Others/ch%203.html",
        "sizeInBytes": 63849
      },
      {
        "id": "LAB 1-2-3.html",
        "title": "LAB 1 2 3",
        "filename": "LAB 1-2-3.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20302/Others/LAB%201-2-3.html",
        "sizeInBytes": 76113
      },
      {
        "id": "LAB 4.html",
        "title": "LAB 4",
        "filename": "LAB 4.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20302/Others/LAB%204.html",
        "sizeInBytes": 60173
      },
      {
        "id": "lecture 1 to 4.html",
        "title": "Lecture 1 To 4",
        "filename": "lecture 1 to 4.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20302/Others/lecture%201%20to%204.html",
        "sizeInBytes": 56674
      }
    ]
  },
  {
    "id": "cse-345",
    "code": "CSE 345",
    "title": "CSE 345",
    "chapters": [
      {
        "id": "ch-1-2.pdf",
        "title": "Ch 1 2",
        "filename": "ch-1-2.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20345/Chapters/ch-1-2.pdf",
        "sizeInBytes": 6884301
      },
      {
        "id": "ch-3-4.pdf",
        "title": "Ch 3 4",
        "filename": "ch-3-4.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20345/Chapters/ch-3-4.pdf",
        "sizeInBytes": 12014109
      },
      {
        "id": "ch-5.pdf",
        "title": "Ch 5",
        "filename": "ch-5.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20345/Chapters/ch-5.pdf",
        "sizeInBytes": 5841231
      },
      {
        "id": "ch-6-7.pdf",
        "title": "Ch 6 7",
        "filename": "ch-6-7.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20345/Chapters/ch-6-7.pdf",
        "sizeInBytes": 8658104
      }
    ],
    "others": [
      {
        "id": "ch_1_2.html",
        "title": "Ch 1 2",
        "filename": "ch_1_2.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20345/Others/ch_1_2.html",
        "sizeInBytes": 89765
      },
      {
        "id": "ch_3_4.html",
        "title": "Ch 3 4",
        "filename": "ch_3_4.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20345/Others/ch_3_4.html",
        "sizeInBytes": 109462
      },
      {
        "id": "ch 5.html",
        "title": "Ch 5",
        "filename": "ch 5.html",
        "type": "HTML",
        "extension": "html",
        "url": "/materials/CSE%20345/Others/ch%205.html",
        "sizeInBytes": 63691
      },
      {
        "id": "LAB3_Pre_Lab_CSE345.pdf",
        "title": "LAB3 Pre Lab CSE345",
        "filename": "LAB3_Pre_Lab_CSE345.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/CSE%20345/Others/LAB3_Pre_Lab_CSE345.pdf",
        "sizeInBytes": 161815
      }
    ]
  },
  {
    "id": "gen-203",
    "code": "GEN 203",
    "title": "GEN 203",
    "chapters": [
      {
        "id": "Lecture 1_Environmental Sustainability Intro (updated) (1).pdf",
        "title": "Lecture 1 Environmental Sustainability Intro (updated) (1)",
        "filename": "Lecture 1_Environmental Sustainability Intro (updated) (1).pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/GEN%20203/Chapters/Lecture%201_Environmental%20Sustainability%20Intro%20(updated)%20(1).pdf",
        "sizeInBytes": 3069274
      },
      {
        "id": "Lecture 2 Environmental Pllution-compressed.pdf",
        "title": "Lecture 2 Environmental Pllution Compressed",
        "filename": "Lecture 2 Environmental Pllution-compressed.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/GEN%20203/Chapters/Lecture%202%20Environmental%20Pllution-compressed.pdf",
        "sizeInBytes": 20473433
      }
    ],
    "others": []
  },
  {
    "id": "gen-209",
    "code": "GEN 209",
    "title": "GEN 209",
    "chapters": [
      {
        "id": "1. Social Psychology Intro.pdf",
        "title": "1. Social Psychology Intro",
        "filename": "1. Social Psychology Intro.pdf",
        "type": "PDF",
        "extension": "pdf",
        "url": "/materials/GEN%20209/Chapters/1.%20Social%20Psychology%20Intro.pdf",
        "sizeInBytes": 1173091
      }
    ],
    "others": []
  }
];
